import React from "react";
import { useEffect } from "react";
import AnimationThree from "../../animation3D/Animation3D";
import GridWithCones from "./testTHREE";
import { Input } from "semantic-ui-react";

const Diamonds = () => {
  useEffect(() => {
    //const anim = new AnimationThree();
    //anim.init();
  }, []);

  return (
    <section
      style={{
        width: "100%",
        height: "50vh",
        position: "relative",
        zIndex: "20",
      }}
    >
      <div
      className="diamondsContainer"
        
      >
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        /><img
        className="diamond"
        src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
        alt=""
      />
      <img
        className="diamond"
        src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
        alt=""
      />
      <img
        className="diamond"
        src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
        alt=""
      />
      <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
      <img
        className="diamond"
        src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
        alt=""
      />
      <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://cdn.dribbble.com/users/2924953/screenshots/7027280/media/96974373b2f347bb98a0c694cc85acee.gif"
          alt=""
        />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />
        <img className="diamond" src="https://i.gifer.com/ClVd.gif" alt="" />
        <img
          className="diamond"
          src="https://media.tenor.com/mHNru1dCsVUAAAAC/diamond-mineral.gif"
          alt=""
        />

      </div>
      <div className="newsLetter row">
        <div className="col-6 glassBox">
          <h5 className="newsLetterSmallTitle">STAY UP TO DATE</h5>
          <h5 className="newLetterTitle">Get our newsletter</h5>
          <Input
            icon={{ name: "search", circular: true, link: true }}
            placeholder="Enter you email"
            className="newsLetterInput"
          />
        </div>
      </div>
    </section>
  );
};

export default Diamonds;
